### ISSUE TITLE
Support for Vue file

### ISSUE THREAD

**Issue by kuntau** [tomtom/tcomment_vim#176] opened 2016-10-27 19:03 UTC
The `.vue` have  multiple format in it `javascript, html and css`, to make matter worse it also support preprocessor `jade, pug, stylus, sass` on the very same file.

What I got for comment only html comment `<!-- -->`

There is issue opened in [posva/vim-vue](https://github.com/posva/vim-vue) (for multiple syntax highlighting) which address the same problem posva/vim-vue#17

Maybe something can be worked out

**Comment by adriaanzon** [comment] 2017-02-02 15:27
This change https://github.com/posva/vim-vue/pull/42 seems to have taken care of it. It works for me now.

**Comment by tomtom** [comment] 2017-02-09 15:30
I'm sorry I totally missed out on this issue.

Since it seems to be fixed in vim-vue, I'll close this issue.

**Closed by tomtom** 2017-02-09 15:30 UTC

**Comment by adriaanzon** [comment] 2017-03-26 22:19
We decided to revert the `vue.html.javascript.css` filetype to `vue`, because it caused too many problems with other plugins.

I can make a pull request to support this again.

**Comment by tomtom** [comment] 2017-03-27 18:26
This would be very much appreciated. Thanks!

**Comment by smackesey** [comment] 2019-02-12 18:56
My vue files work fine for the most part *except* for when I'm using `pug` as an alternate templating language. The `commentstring` for `pug` is `// %s` (i.e. javascript-style). But in a Vue SFC `pug` template block I get weird behavior:

    <template lang="pug">
      div
    </template>

After line-commenting on `div` once....

    <template lang="pug">
      
    </template>

After line-commenting on the commented line...

    <template lang="pug">
      // 
    </template>

So it looks like it is using the default filetype `commentstring` once, but then switching to the context-aware `commentstring` if I'm commenting an already-commented line...?

**Comment by tomtom** [comment] 2019-02-15 07:05
> So it looks like it is using the default filetype |commentstring| once, 
> but then switching to the context-aware |commentstring| if I'm 
> commenting an already-commented line...?

If you have the current head version of tcomment installed, please read 
`:h tcomment-debug`, place the cursor at the position in question and 
`:call tcomment#debug#CollectInfo()`. If you use an older version, 
please use

     echom 'TCOMMENT: &ft =' &filetype
     echom 'TCOMMENT: ft  =' tcomment#filetype#Get()
     echom 'TCOMMENT: stx =' tcomment#syntax#GetSyntaxName(line('.'), 
col('.'))
     echom 'TCOMMENT: ct  =' string(tcomment#GuessCommentType())

And post the result here. Thanks!

**Comment by smackesey** [comment] 2019-02-18 20:14
Here is the requested output:

```
TCOMMENT: &ft = vue
TCOMMENT: ft  = vue
TCOMMENT: stx = htmlTagName
Error detected while processing function tcomment#debug#CollectInfo[5]..tcomment#GuessCommentType[7]..tcomment#filetype#Guess[42]..tcomment#syntax#GetSyntaxName:
line    7:
E716: Key not present in Dictionary: filetype =~ ft_rx
TCOMMENT: ct  = -1
```

**Comment by tomtom** [comment] 2019-02-19 04:55
Sorry for not having tested that.

Is this the result from this?

    <template lang="pug">
      
    </template>

I would expect the "<!--" to have some unexpected syntax name.

**Comment by smackesey** [comment] 2019-02-19 16:04
My first post was the output from:

```
<template lang="pug">
  div
</template>
```

For this:

```
<template lang="pug">
  <!-- div -->
</template>
```

The output is:

```
TCOMMENT: &ft = vue
TCOMMENT: ft  = vue
TCOMMENT: stx = pugHtmlConditionalComment
Error detected while processing function tcomment#debug#CollectInfo[5]..tcomment#GuessCommentType[7]..tcomment#filetype#Guess[42]..tcomment#syntax#GetSyntaxName:
line    7:
E716: Key not present in Dictionary: filetype =~ ft_rx
TCOMMENT: ct  = -1
```

In both cases the cursor is positioned on the first character of the middle line.

**Comment by tomtom** [comment] 2019-02-19 17:15
> stx = pugHtmlConditionalComment

Since the comment definition for the pug filetype is

     call tcomment#type#Define('pug', '//- %s')

This should result in

     //- 

You'd expect to uncomment the comment though.

Where is pugHtmlConditionalComment used in the document? Does your 
plugin somehow distinguish between normal html comments and pug 
conditional comments -- whatever that is. Or are the all just comments?

I don't know pug.

**Comment by smackesey** [comment] 2019-02-19 19:02
I'm not the author of the `pug` filetype plugin so my knowledge is limited. Here is my understanding of the situation though.

`<!-- PUG CODE -->` is a special kind of comment in pug (a "conditional comment"). That's presumably why attempting to comment `<!-- div -->` shows `pugHtmlConditionalComment` for `stx`. However, these conditional comments are an alternative and should not be toggled by the main comment mapping. The way it should work for a line with just `div` on it is this:

`div` --toggle-comment--> `//- div` --toggle-comment-> `div`.

And indeed, tcomment correctly works just like this in a standalone `.pug` file. The output of the `:call tcomment#debug#CollectInfo()`command on a line with just `div` in a standalone pug file is:

```
TCOMMENT: &ft = pug
TCOMMENT: ft  = pug
TCOMMENT: stx = htmlTagName
TCOMMENT: ct  = {'commentstring': '<!-- %s -->', 'replacements': {'&': '&#38;', '-': '&#45;'}, 'mode': '', 'filetype': 'html'}
```

The issue is that the behavior is for some reason different inside a `pug` block in a `.vue` file.
